# Generated by Django 4.1.7 on 2023-03-13 10:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import drilling_schedule.csv_converter


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_schedule', models.FileField(upload_to='drilling_schedules/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'], message='Only *.csv files allowed')])),
                ('version', models.CharField(max_length=20, unique=True)),
                ('is_converted', models.BooleanField(default=False)),
            ],
            bases=(models.Model, drilling_schedule.csv_converter.CSVToInstance),
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('drilling_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pads', to='drilling_schedule.drillingschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('drilling_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rigs', to='drilling_schedule.drillingschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('aim', models.CharField(max_length=20)),
                ('drilling_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='drilling_schedule.drillingschedule')),
                ('pad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='drilling_schedule.pad')),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='drilling_schedule.rig')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('meters_drilled', models.FloatField()),
                ('drilling_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='drilling_schedule.drillingschedule')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='drilling_schedule.well')),
            ],
        ),
        migrations.AddConstraint(
            model_name='well',
            constraint=models.UniqueConstraint(fields=('name', 'drilling_schedule'), name='unique_well'),
        ),
        migrations.AddConstraint(
            model_name='rig',
            constraint=models.UniqueConstraint(fields=('name', 'drilling_schedule'), name='unique_rig'),
        ),
        migrations.AddConstraint(
            model_name='pad',
            constraint=models.UniqueConstraint(fields=('name', 'drilling_schedule'), name='unique_pad'),
        ),
    ]
