# Generated by Django 4.1.7 on 2023-02-18 18:45

from django.db import migrations, models
import django.db.models.deletion
import drilling_schedule.csv_converter


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_schedule', models.FileField(upload_to='drilling_schedules/')),
                ('version', models.CharField(max_length=20)),
                ('converted', models.BooleanField(default=False)),
            ],
            bases=(models.Model, drilling_schedule.csv_converter.CSVToInstance),
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('drilling_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pads', to='drilling_schedule.drillingschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('drilling_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rigs', to='drilling_schedule.drillingschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('aim', models.CharField(max_length=20)),
                ('drilling_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='drilling_schedule.drillingschedule')),
                ('pad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='drilling_schedule.pad')),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='drilling_schedule.rig')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('meters_drilled', models.FloatField()),
                ('drilling_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='drilling_schedule.drillingschedule')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='drilling_schedule.well')),
            ],
        ),
    ]
