# Generated by Django 4.1.7 on 2023-03-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drilling_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drillingschedule',
            old_name='converted',
            new_name='is_converted',
        ),
    ]
